name: basil-godbolt

services:
  godbolt:
    image: ghcr.io/uq-pac/basil-godbolt-docker
    restart: always
    ports:
      - "10240:10240"
    environment:
      GTIRB_SEM_SOCKET: "/run/gts/aslp_rpc_socket"
    volumes:
      - gtirb_sem_socket:/run/gts
      - godbolt:/app/storage
    command: |
      /usr/bin/_exec compiler-explorer --language=c++,c,boogie

  gts:
    image: ghcr.io/uq-pac/gtirb-semantics-server
    restart: always
    environment:
      GTIRB_SEM_SOCKET: "/run/gts/aslp_rpc_socket"
    volumes:
      - gtirb_sem_socket:/run/gts

volumes:
  gtirb_sem_socket:
  godbolt:
