{ lib
, fetchFromGitHub
, buildDunePackage
  # pkgs
  # ocamlPackages
, aslp
  # for testing
, testers
, aslp_offline
}:

buildDunePackage {
  pname = "aslp_offline";
  version = aslp.version;

  minimalOCamlVersion = "4.14";

  src = aslp.src;

  checkInputs = [ ];
  nativeCheckInputs = [ ];
  buildInputs = [ ];
  nativeBuildInputs = [ aslp ];
  propagatedBuildInputs = [ aslp ];

  doCheck = true;

  outputs = [ "out" "dev" ];

  passthru = {
    tests.aslp-server = testers.testVersion {
      package = aslp_offline;
      command = "command -v ${aslp_offline.meta.mainProgram}";
      version = "asloff-sem";
    };
  };

  meta = {
    homepage = "https://github.com/UQ-PAC/aslp";
    description = "AArch64 lifter generated by ASLp by offline partial evaluation";
    maintainers = with lib.maintainers; [ katrinafyi ];
    mainProgram = "asloff-sem";
  };
}
