{ lib
, fetchFromGitHub
, buildDunePackage
  # pkgs
  # ocamlPackages
, aslp_web
, zarith_stubs_js
, js_of_ocaml
, js_of_ocaml-ppx
  # for testing
, testers
, aslp_offline
}:

buildDunePackage {
  pname = "aslp_offline_js";
  version = aslp_web.version;

  minimalOCamlVersion = "5.0";

  src = aslp_web.src;

  checkInputs = [ ];
  nativeCheckInputs = [ ];
  buildInputs = [ aslp_offline js_of_ocaml zarith_stubs_js js_of_ocaml-ppx ];
  nativeBuildInputs = [ js_of_ocaml ];
  propagatedBuildInputs = [ ];

  doCheck = true;

  outputs = [ "out" "dev" ];

  meta = {
    homepage = "https://github.com/katrinafyi/aslp-web";
    description = "AArch64 lifter generated by ASLp by offline partial evaluation (offline lifter component)";
    maintainers = with lib.maintainers; [ katrinafyi ];
  };
}
