on:
  workflow_call:
    inputs:
      pkg: { required: true, type: string }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with: { nix_path: 'nixpkgs=channel:nixos-unstable' }
    - uses: cachix/cachix-action@v12
      with: { name: pac-nix, authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}' }

    - run: nix-build -A ${{inputs.pkg}}
    - name: nix-build -A ${{inputs.pkg}}.tests -o result-tests
      run: |
        if nix-instantiate --eval -A ${{inputs.pkg}}.tests; then
          nix-build -A ${{inputs.pkg}}.tests -o result-tests
        fi
    - run: ls -l

