name: "build Nix packages"
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      push: { type: boolean, default: false }
      patches-url: { type: string }
  workflow_call:
    inputs:
      push: { type: boolean, default: false, required: false }
      patches-url: { type: string, required: false }

jobs:
  update-check:
    if: ${{ ! inputs.patches-url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - run: nix build .#update
    - run: nix run .#update -- check

  build:
    strategy:
      fail-fast: false
      matrix:
        # end-user packages to ci build for cache
        pkg: 
          [aslp, bap-aslp, bap-primus, basil,
          retdec-uq-pac, asl-translator,
          gtirb-semantics, ddisasm, 
          retdec5, remill, alive2-aslp, alive2-regehr,
          planter,
          aslp_web, godbolt
        ]
    runs-on: ubuntu-latest

    defaults:
      run: { shell: "bash -ex -o pipefail {0}" }
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with: { name: pac-nix, authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}', skipPush: "${{ github.ref != 'refs/heads/main' }}" }

    - name: Apply staged patch commits
      if: ${{ inputs.patches-url }}
      run: |
        shopt -s nullglob
        set -x

        wget --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -O patches.zip \
          '${{ inputs.patches-url }}'

        unzip patches.zip -d prev-patches

        git config user.name 'github-actions[bot]'
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

        for f in prev-patches/*; do git am "$f"; done

    - name: Check for meta.broken
      run: |
        broken="$(nix eval --json .#${{ matrix.pkg }}.meta.broken)"
        echo "bool=$broken" > "$GITHUB_OUTPUT"
        echo NIXPKGS_ALLOW_BROKEN="$("$broken" && echo 1 || echo 0)" > "$GITHUB_ENV"
      id: broken

    - run: ./nix-cached.sh build --impure .#${{matrix.pkg}}
      id: build
      continue-on-error: ${{ fromJSON(steps.broken.outputs.bool) }}
      
    - name: Run nix build .#${{matrix.pkg}}.tests
      id: test
      run: |
        for test in $(nix eval --impure .#${{matrix.pkg}}.tests --json | jq -r keys[]); do
          t=.#${{matrix.pkg}}.tests.$test 
          ./nix-cached.sh build --impure "$t" --no-link
        done
      continue-on-error: ${{ fromJSON(steps.broken.outputs.bool) }}
      if: steps.build.outcome == 'success'
      
    - name: Report status of broken packages
      run: |
        echo '::warning title=${{ matrix.pkg }}::broken package has status build=${{steps.build.outcome}}, test=${{steps.test.outcome}}'
      if: ${{ fromJSON(steps.broken.outputs.bool) }}
    - run: ls -l

  result:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - name: Aggregate matrix results
      run: |
        set -x
        result="${{ needs.build.result }}"
        [[ $result == success || $result == skipped ]]

    - name: Apply staged patch commits
      if: ${{ inputs.patches-url }}
      run: |
        shopt -s nullglob
        set -x

        wget --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O patches.zip \
          '${{ inputs.patches-url }}'

        unzip patches.zip -d prev-patches

        git config user.name 'github-actions[bot]'
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

        for f in prev-patches/*; do git am "$f"; done

    - run: git push
      if: ${{ inputs.push }}
