name: "build Nix packages"
on:
  pull_request:
  push:
  schedule:
  - cron: '53 20 * * *'  # AEST 6:53 am
  workflow_dispatch:
jobs:
  sources:
    if: |
      github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      && contains('schedule workflow_dispatch', github.event_name)
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        pkg: [asli, bap-asli-plugin, bap-uq-pac, basil]
    uses: ./.github/workflows/nix.yml
    with:
      pkg: ${{matrix.pkg}}
    secrets: inherit

  tools:
    needs: sources
    if: ${{ !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        pkg: [aslp, bap-aslp, bap-uq-pac, basil]
    uses: ./.github/workflows/build.yml
    with:
      pkg: ${{matrix.pkg}}
    secrets: inherit

