name: "build Nix packages"
on:
  pull_request:
  push:
  # schedule:
  # - cron: '53 19 * * *'  # AEST 5:53 am
  workflow_run:
    workflows: [update Nix packages]
    types: [completed]
  workflow_dispatch:

jobs:
  update-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with: { nix_path: 'nixpkgs=channel:nixpkgs-unstable' }
    - run: |
        nix-shell ./update-shell.nix --run './update.py check'

  build:
    strategy:
      fail-fast: false
      matrix:
        # end-user packages to ci build for cache
        pkg: 
          [aslp, bap-aslp, bap-primus, basil,
          alive2, retdec-uq-pac, asl-translator]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with: { nix_path: 'nixpkgs=channel:nixpkgs-unstable' }
    - uses: cachix/cachix-action@v12
      with: { name: pac-nix, authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}' }

    - run: nix-build -A ${{matrix.pkg}}
    - name: Run nix-build -A ${{matrix.pkg}}.tests -o result-tests
      run: |
        if nix-instantiate --eval -A ${{matrix.pkg}}.tests; then
          nix-build -A ${{matrix.pkg}}.tests -o result-tests
        fi
    - run: ls -l
