name: "Build Nix packages"
on:
  pull_request:
  push:
  schedule:
  - cron: '0 0 * * *'
jobs:
  nix:
    strategy:
      max-parallel: 1
      matrix:
        pkg: [aslp, bap-aslp, basil, bap-uq-pac]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: pac-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build ./pkgs.nix -A ${{matrix.pkg}} -o result-${{matrix.pkg}} 
    - run: ls -l
