name: "Build Nix packages"
on:
  pull_request:
  push:
  schedule:
  - cron: '53 21 * * *'  # AEST 7:53 am
jobs:
  nix:
    strategy:
      matrix:
        pkg: [aslp, bap-aslp, basil, bap-uq-pac]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: pac-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build -A ${{matrix.pkg}}
    - name: nix-build -A ${{matrix.pkg}}.tests -o result-tests
      run: |
        if nix-instantiate --eval -A ${{matrix.pkg}}.tests; then
          nix-build -A ${{matrix.pkg}}.tests -o result-tests
        fi
    - run: ls -l
  update-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: pac-nix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./update.sh check
