name: "update Nix packages"
on:
  schedule:
  - cron: '53 18 * * *'  # AEST 4:53 am
  workflow_dispatch:

jobs:
  update:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        pkg: [asli, bap-asli-plugin, bap-uq-pac, basil]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with: { nix_path: 'nixpkgs=channel:nixos-unstable' }
    - uses: cachix/cachix-action@v12
      with: { name: pac-nix, authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}' }

    - run: nix-build ./update-shell.nix
    - run: |
        nix-shell ./update-shell.nix --run './update.py check -A ${{matrix.pkg}}'

    - run: |
        git pull
        git config user.name 'github-actions[bot]'
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - run: |
        nix-shell ./update-shell.nix --run './update.py do-upgrade -A ${{matrix.pkg}}'
    - run: git push

