name: "update Nix packages"
on:
  schedule:
  - cron: '53 18 * * *'  # AEST 4:53 am
  workflow_dispatch:

jobs:
  update:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        pkg: [asli, bap-asli-plugin, bap-primus, basil, gtirb-semantics,
              asl-translator, alive2-aslp, alive2-regehr]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with: { name: pac-nix, authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}' }

    - run: |
        nix run .#update -- check -A ${{matrix.pkg}}

    - run: |
        git pull
        git config user.name 'github-actions[bot]'
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - run: |
        nix run .#update -- do-upgrade -A ${{matrix.pkg}}
    - run: git push

