name: "update Nix packages"
on:
  schedule:
  - cron: '53 18 * * 0-4'  # AEST 4:53 am
  workflow_dispatch:
    inputs:
      do-commit:
        description: 'whether to commit updated changes'
        type: choice
        default: 'no-commit'
        options:
          - 'commit'
          - 'no-commit'

env:
  COMMIT: ${{ github.sha }}
  DO_COMMIT: ${{ inputs.do-commit == "commit" || github.event_name == "schedule" }}

jobs:
  update:
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        pkg: [asli, bap-asli-plugin, bap-primus, basil, gtirb-semantics,
              asl-translator, alive2-aslp, alive2-regehr, aslp_web, compiler-explorer]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with: { name: pac-nix, authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}' }

    - uses: actions/download-artifact@v4
      with:
        pattern: 'partial-patches-*'
        merge-multiple: true
        path: prev-patches

    - run: |
        git config user.name 'github-actions[bot]'
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        mkdir -p prev-patches

    - run: git am prev-patches

    - run: |
        nix run .#update -- check -A ${{matrix.pkg}}

    - run: |
        nix run .#update -- do-upgrade -A ${{matrix.pkg}}
    - run: |
        git format-patch $COMMIT -o new-patches

    - uses: actions/upload-artifact@v4
      with:
        name: partial-patches-${{matrix.pkg}}
        path: new-patches
        if-no-files-found: ignore

  collate:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [ update ]
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: 'partial-patches-*'
        merge-multiple: true
        path: prev-patches

    - uses: geekyeggo/delete-artifact@v5
      with:
        name: 'partial-patches-*'

    - uses: actions/upload-artifact@v4
      with:
        name: all-patches-${{ env.DO_COMMIT && 'commit' || 'no-commit' }}
        path: prev-patches
        if-no-files-found: ignore

